### ISSUE TITLE
get away from storing Tier0 configuration in flat python file

### ISSUE THREAD

**Issue by hufnagel** [dmwm/T0#3092]
The Tier0 configuration (OfflineConfiguration.py) is currently stored in a flat python file. We want to get away from that eventually.

Interaction with the configuration is already factored out and only done in the two components which call an imported method to read the configuration.

Whatever we replace this with should preferably not change the return format of the config loading method, just replace the backend storage.

**Comment by germanfgv** [comment]
We are not planning to move away from the pyton config file any time soon.

**Comment by drsm79** [comment]
Hehehe 11 years later I'd say not! ;)
