### ISSUE TITLE
streamer file cleanup in Tier0

### ISSUE THREAD

**Issue by hufnagel** [dmwm/T0#3116]
This is a place holder ticket. At the moment, streamer files are stored on a separate castor pool and cleanup is taken care of by a 30 day garbage collection policy. So nothing to do for us.

In the long run streamers will go to EOS. Does EOS support garbage collection or special garbage collection per directory ? If not, we would need to handle the cleanup ourself, either from within the Tier0 or running externally (manual, cron jobs etc).

**Comment by germanfgv** [comment]
This script has already been implemented and we've been using it for years.
