### ISSUE TITLE
support switch of Tier0 head node

### ISSUE THREAD

**Issue by hufnagel** [dmwm/T0#3125]
Restarting from scratch when loosing a head node is not an option for the Tier0. We need to be able install a new Tier0/WMAgent on a different machine, point it to the Oracle instance of the old system and resync from there. For the most part that should be possible, but the WMAgent design stores some files on the local filesystem that are required (WMSpecs etc).

For the WMSpecs I imagine looping over all Repack, Express and PromptReco workflows that are not fully finished and recreate the WMSpecs etc from information in RunConfig.

If there are job directories etc we rely on, we need to be able to retry the jobs so they can succeed.

**Comment by germanfgv** [comment]
We have no plans to create this feature any longer
