### ISSUE TITLE
proper unit tests for edge cases in run/lumi closeout

### ISSUE THREAD

**Issue by hufnagel** [dmwm/T0#3211]
This is a placeholder ticket for more extensive unit tests covering lumi and run closeout. What is currently in place in the Tier0Feeder unit test covers the normal conditions, using a run picked at random and checking that everything works.

Problem is, what we are really interested in are the cases where conditions are not normal. Given that such conditions are temporary and fix themself or are fixed manually later in the StorageManager database, there is no input to test these cases though.

Will bring up the issue with the StorageManager team. We might have to setup some special StorageManager database records (either fake runs/lumis in the standard SM DB or another SM DB altogether) to be able to test everything we want.

**Comment by germanfgv** [comment]
Outdated issue. Unit test will be reformulated.
