### ISSUE TITLE
check argument type in job splitters

### ISSUE THREAD

**Issue by hufnagel** [dmwm/T0#3660]
Had an interesting bug today (#3659) where instead of arg = 123 I passed arg = 123, to a job splitter. Strangely enough this worked (no crashes/failures), but lead to wrong behaviour in the splitting algorithm. "123," is a tuple and apparently you can do comparisons between tuple and int just fine, the result will just be different from what you expect.

Should probably check the input type of the arguments passed to the splitting algorithms and fail if they are wrong.

**Comment by germanfgv** [comment]
Python3 no longer allows for comparison operations between different data types. This change is no longer required.
