### ISSUE TITLE
Optimize Tier0Feeder.FeedStreamers DAO

### ISSUE THREAD

**Issue by hufnagel** [dmwm/T0#4042]
The Tier0Feeder.FeedStreamers DAO at the moment uses two queries, first one to feed streamer files into the relevant filesets and then a second one to update the status of the streamer files. I could not find a way to do this in one query. Having this done in a single query or a stored procedure might be faster.

Not a priority at all, just a placeholder.

**Comment by germanfgv** [comment]
We have no planes to move in this direnction
