### ISSUE TITLE
add more information in couchdb 

### ISSUE THREAD

**Issue by ticoann** [dmwm/T0#4096]
Currently only request name and run number is recorded about the workflow (other then job information).
https://github.com/ticoann/T0/blob/t0_wmstats/src/python/T0Component/Tier0Feeder/Tier0FeederPoller.py#L287

FYI. Production workflow information

https://cmsweb.cern.ch/couchdb/_utils/document.html?reqmgr_workload_cache/fabozzi_RVCMSSW_7_2_0_pre8SoftQCDinelastic_13TeV_pythia8_141009_194605_1007

**Comment by hufnagel** [comment]
Is this still relevant @ticoann ?

**Comment by ticoann** [comment]
Yes, but it depends, I think there are only few information is in request document for Tier0 request. 
RequestName, Run number, status.  I am not sure what is relevant information but we could add more information as well. Acquistion era, global tag, etc

**Comment by germanfgv** [comment]
Outdated issue. We will discuss Couch and  WMStats changes with DMWM using their new channels of communication
