### ISSUE TITLE
change the wmbs_location_senames table

### ISSUE THREAD

**Issue by ticoann** [dmwm/T0#4282]
Once this pull request is tested and merged T0 code need to be changed the same way
https://github.com/dmwm/WMCore/pull/6365

**Comment by ticoann** [comment]
@alexanderrichards, Alex, could you take care of this issue?

**Comment by alexanderrichards** [comment]
thanks @ticoann I don't seem to have access to assign myself to this issue. I guess this because I don't have access to the T0 repo. Could you assign me so that I can keep track of it.
