### ISSUE TITLE
fix Express AlcaSkim task to use single core

### ISSUE THREAD

**Issue by hufnagel** [dmwm/T0#4336]
https://github.com/dmwm/WMCore/pull/7395

changed how number of cores has to be set inside a specs for individual tasks. Needs to use taskConf now.

https://github.com/dmwm/T0/blob/master/src/python/T0/WMSpec/StdSpecs/Express.py#L198

**Comment by amaltaro** [comment]
Maybe we should move these 2 specs into WMCore repo instead? Otherwise such problems will certainly happen in the future again.
