### ISSUE TITLE
Where is the real Tier0 config?

### ISSUE THREAD

**Issue by davidlange6** [dmwm/T0#4355]
the one in this repo looks to be obsolete now

**Comment by drkovalskyi** [comment]
we have a copy of actual Tier0 configuration for both head nodes available on the web

**Comment by davidlange6** [comment]
where?

**Comment by drkovalskyi** [comment]
http://cmst1.web.cern.ch/CMST1/tier0/ProdOfflineConfiguration_0313.py
http://cmst1.web.cern.ch/CMST1/tier0/ProdOfflineConfiguration_0314.py

**Comment by davidlange6** [comment]
Thanks - maybe 

https://github.com/dmwm/T0/blob/master/etc/ProdOfflineConfiguration.py

can be removed if it is no longer updated. (I'll fix the documentation that I'm aware of)

**Comment by drkovalskyi** [comment]
It's a reference configuration and we will keep updating it. Unfortunately at the moment we have too many important issues to track, so it was not updated for a few weeks.

**Comment by davidlange6** [comment]
think automation... please let people know when the old source of information is back to being kept up to date. Thanks
