### ISSUE TITLE
Condition_t is not working properly

### ISSUE THREAD

**Issue by andresfelquintero** [dmwm/T0#4486]
Condition_t located on https://github.com/andresfelquintero/T0/blob/Unit_test_Condition_t/test/python/T0_t/WMBS_t/JobSplitting_t/Condition_t.py#L228 always fails because it is not able to close the file and the condition on Line 228 is not met.

**Comment by germanfgv** [comment]
The condition is not met because markPromptCalibrationFinishedDAO does not find runs/streams pairs that can be marked as finished. This is due to the fact that there is istill a file in wmbs_sub_files_acquired.subscription that belongs to the subscription.
