### ISSUE TITLE
Open files/urls with context manager

### ISSUE THREAD

**Issue by andresfelquintero** [dmwm/T0#4498]
According to Alan, we should properly close file descriptors, as shown in https://github.com/dmwm/WMCore/pull/9186 . For T0 do we need to do the same? which files should need more attention?

**Comment by hufnagel** [comment]
Only two instances of open to replace in the T0 code

https://github.com/dmwm/T0/blob/master/src/python/T0/ConditionUpload/ConditionUploadAPI.py#L248

https://github.com/dmwm/T0/blob/master/src/python/T0/ConditionUpload/ConditionUploadAPI.py#L251

**Comment by andresfelquintero** [comment]
I made a pull request with these changes https://github.com/dmwm/T0/pull/4500

**Comment by vytjan** [comment]
Thanks Andres, tested and merged #4501
