### ISSUE TITLE
Replay test with 12_1_0_pre3

### ISSUE THREAD

**Issue by qliphy** [dmwm/T0#4605]
As discussed with @germanfgv @drkovalskyi  and at ORP meeting yesterday, we (@perrotta and me) will launch replay test with 12_1_0_pre3.  We would like to collect information for that.
@francescobrivio  @tvami @boudoul @rappoccio

Runs  (default setting): 
- 341169,341754,338628,338714,342154 

GTs:   (following https://github.com/dmwm/T0/pull/4602)
- Express: 113X_dataRun3_Express_Candidate_2021_06_21_16_58_57
- Prompt: 113X_dataRun3_Prompt_Candidate_2021_06_21_16_59_39

Others: ?

**Comment by germanfgv** [comment]
@francescobrivio  Do you think it would make sense to wait for 120X GTs?. Also, I'll suggest removing 338714, as I don't think we will benefit of processing 2020 data but it would significantly increase the consumption of resourses. and lenght of the replay.

**Comment by francescobrivio** [comment]
> @francescobrivio Do you think it would make sense to wait for 120X GTs?. Also, I'll suggest removing 338714, as I don't think we will benefit of processing 2020 data but it would significantly increase the consumption of resourses. and lenght of the replay.

@germanfgv 
- I agree with the removal of 338714
- I don't think it's beneficial to wait for 120X GTs, we will need ~1 week for making those GTs and they will be in any case tested once the new release for CRAFT/PilotBeam will be created

**Comment by qliphy** [comment]
@francescobrivio @germanfgv Thanks!
I have made a PR:  https://github.com/dmwm/T0/pull/4607
let me know if you have any further comment before we launch the test.

**Comment by germanfgv** [comment]
@francescobrivio I just noticed that we have not been asked to save the run 344518. Is that right or did I missed something?

**Comment by francescobrivio** [comment]
> @francescobrivio I just noticed that we have not been asked to save the run 344518. Is that right or did I missed something?

@germanfgv good point! thanks for checking! 
I'm looking at https://twiki.cern.ch/twiki/bin/view/CMSPublic/CompOpsTier0TeamReplayGoodRuns but I don't see CRUZET 2021 runs, can you list the runs that have been saved from CRUZET? possibily we should use one that include all subdetectors.

**Comment by germanfgv** [comment]
@francescobrivio You are right. We'll update the list. In the mean time these are the available CRUZET runs:
```
               343498, #CRUZET
               343082, #CRUZET (FPIX, TEC, TOB, HCAL, CSC, DT, RPC, GEM)
               343925, #CRUZET (small cosmics)
               344063  #CRUZET (BPIX, FPIX, TEC, TIBTID, TOB, ECAL, HCAL, CSC, DT, RPC, GEM)

```

**Comment by francescobrivio** [comment]
> @francescobrivio You are right. We'll update the list. In the mean time these are the available CRUZET runs:
> 
> ```
> 343498, #CRUZET
> 343082, #CRUZET (FPIX, TEC, TOB, HCAL, CSC, DT, RPC, GEM)
> 343925, #CRUZET (small cosmics)
> 344063  #CRUZET (BPIX, FPIX, TEC, TIBTID, TOB, ECAL, HCAL, CSC, DT, RPC, GEM)
> ```

I sugges to use `343498` which is the shortest one with all subsystems in!

**Comment by germanfgv** [comment]
Ok @francescobrivio, I'll add it to the replay

**Comment by germanfgv** [comment]
The test was successful, so I'm closing this issue
